### ISSUE TITLE
Создать .env файл

### ISSUE THREAD

**Issue by azya0** [g0lubew-iv/grad-api#1]
Было бы неплохой идеей вынести следующий код (из [app.py](https://github.com/g0lubew-iv/grad-api/blob/main/app.py)):

![image](https://github.com/user-attachments/assets/203a9878-04f6-486d-a928-e98b79fb7fc3)

В ```.env``` файл, подгружать который можно с помощью [python-dotenv](https://pypi.org/project/python-dotenv/)

```pip install python-dotenv```

```from dotenv import load_dotenv```
```load_dotenv()```

Далее использовать переменные окружения можно через библиотеку ```os```

Так же хорошей практикой было бы использовать config-класс с помощью [pydantic](https://pypi.org/project/pydantic/)
Вы можете посмотреть [мою реализацию](https://github.com/azya0/Ambulance-dispatcher/blob/main/backend/source/config.py)

**Comment by azya0** [comment]
Стоит отметить, что я видел ```.env``` в ```.gitignore```. Я думаю, что этим вы хотели скрыть поля-токенов. Однако, обычно поля с токенами для API оставляют незаполненными, а остальные, вроде HOST или PORT заполненными. **Так пользователю будет легче редактировать работу программы, не переписывая при этом исходный код.**

**Comment by g0lubew-iv** [comment]
![response](https://github.com/user-attachments/assets/3468d4fe-80a3-4646-9005-b40c87eab8f7)
